version: "3.5"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./../workspaces/spa-backend:/var/www/html
      - ./.docker/nginx/config/:/etc/nginx/conf.d/
      - ./.docker/nginx/log/:/var/log/nginx/
    restart: always
    environment:
      REDIS_HOST: redis
    networks:
      - spa-networks
  php:
    container_name: php
    build: ./.docker/php/build/
    image: php-custom
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./../workspaces/spa-backend:/var/www/html
      - ./.docker/php/log:/var/log/php-fpm
      - ./.docker/php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - spa-networks
  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.docker/proxy/config/:/etc/nginx/conf.d/
      - ./.docker/proxy/log/:/var/log/nginx/
    restart: always
    depends_on:
      - nginx
    networks:
      - spa-networks
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P2ssword1!
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql:rw
    networks:
      - spa-networks
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      REDIS_HOST: redis
    depends_on:
      - mysql
    restart: always
    networks:
      - spa-networks
networks:
  spa-networks:
    external: true
